# Generated by Django 4.2 on 2023-08-17 08:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pond_management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceReg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=255, unique=True)),
                ("device_code", models.CharField(max_length=255, null=True)),
                ("installed_by", models.CharField(max_length=255, null=True)),
                ("installed_at", models.DateTimeField(default=datetime.datetime.now)),
                ("is_active", models.BooleanField(default=True)),
                ("reg_date", models.DateTimeField(default=datetime.datetime.now)),
                ("modify_date", models.DateTimeField(null=True)),
                (
                    "modify_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reg_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reg_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(blank=True, max_length=255, null=True)),
                ("topic", models.CharField(blank=True, max_length=255, null=True)),
                ("message", models.CharField(blank=True, max_length=255, null=True)),
                ("seen_status", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.DateTimeField(default=datetime.datetime.now, null=True),
                ),
                ("notification_at", models.DateTimeField(null=True)),
                ("topic_value", models.FloatField(blank=True, default=0.0, null=True)),
                (
                    "device_reg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="device_management.devicereg",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeviceData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("d_id", models.IntegerField(blank=True, null=True)),
                ("value", models.FloatField(default=0.0, null=True)),
                (
                    "device_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sensor_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "parameter_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, default=datetime.datetime.now, null=True
                    ),
                ),
                ("data_time", models.DateTimeField(null=True)),
                (
                    "obj_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "device_in",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pond_management.pond",
                    ),
                ),
                (
                    "device_reg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="device_management.devicereg",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interval_time", models.IntegerField(default=0, null=True)),
                (
                    "created_at",
                    models.DateTimeField(default=datetime.datetime.now, null=True),
                ),
                (
                    "config_updated_at",
                    models.DateTimeField(default=datetime.datetime.now, null=True),
                ),
                (
                    "config_updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "device_in",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pond_management.pond",
                    ),
                ),
                (
                    "device_reg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="device_management.devicereg",
                    ),
                ),
            ],
        ),
    ]
